FROM postgres:14.2

# ロケール設定
RUN localedef -v -c -i ja_JP -f UTF-8 ja_JP.UTF-8; echo "";
ENV LANG=ja_JP.UTF-8

# タイムゾーン設定
RUN rm -f /etc/localtime && \
    ln -fs /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# vimパッケージ
RUN apt-get update && apt-get install -y vim

# 初期化用SQLとスクリプト
COPY ./docker/deploy/db/01_init.sh /docker-entrypoint-initdb.d/
COPY ./docker/deploy/db/*.sql /tmp/
RUN chown postgres:postgres /tmp/*.sql
RUN chown postgres:postgres /docker-entrypoint-initdb.d/*.sh
