package jp.cstudio.csfw.db;

import java.sql.SQLException;

public interface FWStatement extends AutoCloseable {

  @Override
  void close() throws SQLException;

  boolean isClosed() throws SQLException;

  FWResultSet executeQuery(String sql) throws SQLException;

  int executeUpdate(String sql) throws SQLException;

  int getMaxFieldSize() throws SQLException;

  void setMaxFieldSize(int max) throws SQLException;

  int getMaxRows() throws SQLException;

  void setMaxRows(int max) throws SQLException;

  void setEscapeProcessing(boolean enable) throws SQLException;

  int getQueryTimeout() throws SQLException;

  void setQueryTimeout(int seconds) throws SQLException;

  boolean execute(String sql) throws SQLException;

  FWResultSet getResultSet() throws SQLException;

  int getUpdateCount() throws SQLException;

  boolean getMoreResults() throws SQLException;

  void addBatch(String sql) throws SQLException;

  void clearBatch() throws SQLException;

  int[] executeBatch() throws SQLException;

  int CLOSE_CURRENT_RESULT = 1;

  int KEEP_CURRENT_RESULT = 2;

  int CLOSE_ALL_RESULTS = 3;

  int SUCCESS_NO_INFO = -2;

  int EXECUTE_FAILED = -3;

  int RETURN_GENERATED_KEYS = 1;

  int NO_GENERATED_KEYS = 2;

  boolean getMoreResults(int current) throws SQLException;

  FWResultSet getGeneratedKeys() throws SQLException;

  int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException;

  int executeUpdate(String sql, int columnIndexes[]) throws SQLException;

  int executeUpdate(String sql, String columnNames[]) throws SQLException;

  boolean execute(String sql, int autoGeneratedKeys) throws SQLException;

  boolean execute(String sql, int columnIndexes[]) throws SQLException;

  boolean execute(String sql, String columnNames[]) throws SQLException;

  long getLargeUpdateCount() throws SQLException;

  void setLargeMaxRows(long max) throws SQLException;

  long getLargeMaxRows() throws SQLException;

  long[] executeLargeBatch() throws SQLException;

  long executeLargeUpdate(String sql) throws SQLException;

  long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException;

  long executeLargeUpdate(String sql, int columnIndexes[]) throws SQLException;

  long executeLargeUpdate(String sql, String columnNames[]) throws SQLException;

}
